Testing
Change-Id: If6de0b4f3a0788be836d48c86dfe56848f8d2255

diff --git a/.github/workflows/artifact-testing.yaml b/.github/workflows/artifact-testing.yaml
--- a/.github/workflows/artifact-testing.yaml
+++ b/.github/workflows/artifact-testing.yaml
@@ -1,74 +1,113 @@
 name: CI Tests
 
 on:
-  # push:
+  push:
   workflow_dispatch:
   # pull_request:
   #   types: [opened, edited, synchronize, ready_for_review]
 
 jobs:
-  build-gem5:
+pannotia-tests:
     runs-on: [self-hosted, linux, x64, build]
-    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
-    outputs:
-      build-name: ${{ steps.artifact-name.outputs.name }}
+    continue-on-error: true
+    container: mkjost/testing-gpu-image:latest
+    # needs: build-gem5
+    timeout-minutes: 4320 # 3 days
+    strategy:
+      matrix:
+        test-name: [BC, "Color Max", "Color Max Min", FW, MIS, "PageRank Default", "PageRank (SPMV)", "SSSP (CSR)", "SSSP (ELL)"]
+        include:
+          - working-directory: exit 0
+          - test-name: BC
+            working-directory: exit 1
+          - test-name: "Color Max"
+            working-directory: exit 1
+
     steps:
       - uses: actions/checkout@v3
         with:
           # Scheduled workflows run on the default branch by default. We
           # therefore need to explicitly checkout the develop branch.
           ref: develop
-      - id: artifact-name
-        run: echo "name=$(date +"%Y-%m-%d_%H.%M.%S")-ALL" >> $GITHUB_OUTPUT
-      - name: Build gem5
-        run: |
-          scons build/ALL/gem5.opt -j $(nproc)
-      - uses: actions/upload-artifact@v3
-        with:
-          name: ${{ steps.artifact-name.outputs.name }}
-          path: build/ALL/gem5.opt
-          retention-days: 5
-      - run: echo "This job's status is ${{ job.status }}."
+      # - name: Build gem5.opt
+      #   working-directory: ${{ github.workspace }}
+      #   run: scons build/GCN3_X86/gem5.opt -j4 --ignore-style --duplicate-sources || rm -rf build && scons build/GCN3_X86/gem5.opt -j4 --ignore-style --duplicate-sources
+      # - uses: actions/download-artifact@v3
+        # with:
+        #   name: ${{needs.build-gem5.outputs.build-name}}
+        #   path: build/GCN3_X86
+      # - run: chmod u+x build/GCN3_X86/gem5.opt
+      # - name: checkout gem5 resources
+      #   working-directory: ${{ github.workspace }}
+      #   run: |
+      #     git clone https://gem5.googlesource.com/public/gem5-resources
+      #     cd gem5-resources
+      #     git checkout develop
+      - name: Compile m5ops and x86
+        # working-directory: ${{ github.workspace }}/util/m5
+        run: {matrix.working-directory}
+  # build-gem5:
+  #   runs-on: [self-hosted, linux, x64, build]
+  #   container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
+  #   outputs:
+  #     build-name: ${{ steps.artifact-name.outputs.name }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         # Scheduled workflows run on the default branch by default. We
+  #         # therefore need to explicitly checkout the develop branch.
+  #         ref: develop
+  #     - id: artifact-name
+  #       run: echo "name=$(date +"%Y-%m-%d_%H.%M.%S")-ALL" >> $GITHUB_OUTPUT
+  #     - name: Build gem5
+  #       run: |
+  #         scons build/ALL/gem5.opt -j $(nproc)
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ steps.artifact-name.outputs.name }}
+  #         path: build/ALL/gem5.opt
+  #         retention-days: 5
+  #     - run: echo "This job's status is ${{ job.status }}."
 
-  testlib-long-insttest_se:
-    runs-on: [self-hosted, linux, x64, run]
-    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
-    needs: build-gem5
-    timeout-minutes: 1440 # 24 hours
-    steps:
-    - name: Clean runner
-      run:
-        rm -rf ./* || true
-        rm -rf ./.??* || true
-        rm -rf ~/.cache || true
-    - uses: actions/checkout@v3
-      with:
-        # Scheduled workflows run on the default branch by default. We
-        # therefore need to explicitly checkout the develop branch.
-        ref: develop
-    - uses: actions/download-artifact@v3
-      with:
-        name: ${{needs.build-gem5.outputs.build-name}}
-        path: build/ALL
-    - run: chmod u+x build/ALL/gem5.opt
-    - name: long insttest_se
-      working-directory: ${{ github.workspace }}/tests
-      run: ./main.py run gem5/insttest_se --length=long --skip-build -vv -t $(nproc)
-    - name: create zip of results
-      if: success() || failure()
-      run: |
-        apt-get -y install zip
-        zip -r output.zip tests/testing-results
-    - name: upload zip
-      if: success() || failure()
-      uses: actions/upload-artifact@v3
-      env:
-        MY_STEP_VAR: ${{github.job}}_COMMIT.${{github.sha}}_RUN.${{github.run_id}}_ATTEMPT.${{github.run_attempt}}
-      with:
-        name: ${{ env.MY_STEP_VAR }}
-        path: output.zip
-        retention-days: 7
-    - run: echo "This job's status is ${{ job.status }}."
+  # testlib-long-insttest_se:
+  #   runs-on: [self-hosted, linux, x64, run]
+  #   container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
+  #   needs: build-gem5
+  #   timeout-minutes: 1440 # 24 hours
+  #   steps:
+  #   - name: Clean runner
+  #     run:
+  #       rm -rf ./* || true
+  #       rm -rf ./.??* || true
+  #       rm -rf ~/.cache || true
+  #   - uses: actions/checkout@v3
+  #     with:
+  #       # Scheduled workflows run on the default branch by default. We
+  #       # therefore need to explicitly checkout the develop branch.
+  #       ref: develop
+  #   - uses: actions/download-artifact@v3
+  #     with:
+  #       name: ${{needs.build-gem5.outputs.build-name}}
+  #       path: build/ALL
+  #   - run: chmod u+x build/ALL/gem5.opt
+  #   - name: long insttest_se
+  #     working-directory: ${{ github.workspace }}/tests
+  #     run: ./main.py run gem5/insttest_se --length=long --skip-build -vv -t $(nproc)
+  #   - name: create zip of results
+  #     if: success() || failure()
+  #     run: |
+  #       apt-get -y install zip
+  #       zip -r output.zip tests/testing-results
+  #   - name: upload zip
+  #     if: success() || failure()
+  #     uses: actions/upload-artifact@v3
+  #     env:
+  #       MY_STEP_VAR: ${{github.job}}_COMMIT.${{github.sha}}_RUN.${{github.run_id}}_ATTEMPT.${{github.run_attempt}}
+  #     with:
+  #       name: ${{ env.MY_STEP_VAR }}
+  #       path: output.zip
+  #       retention-days: 7
+  #   - run: echo "This job's status is ${{ job.status }}."
   # build-gem5:
   #   strategy:
   #     matrix:
