testing

diff --git a/.github/workflows/artifact-testing.yaml b/.github/workflows/artifact-testing.yaml
--- a/.github/workflows/artifact-testing.yaml
+++ b/.github/workflows/artifact-testing.yaml
@@ -1,42 +1,42 @@
-name: 'Github Workflow History'
+# name: 'Github Workflow History'
 
-'on':
-  push:
-    inputs:
-      failJob:
-        description: Fail the job?
-        type: boolean
-        required: true
-        default: false
+# 'on':
+#   push:
+#     inputs:
+#       failJob:
+#         description: Fail the job?
+#         type: boolean
+#         required: true
+#         default: false
 
-jobs:
-  exampleJob:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+# jobs:
+#   exampleJob:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
 
-      - name: Pass or fail job
-        run: exit 1
-        if: github.event.inputs.failJob == 'true'
+#       - name: Pass or fail job
+#         run: exit 1
+#         if: github.event.inputs.failJob == 'true'
 
-      - name: Check last job status
-        id: lastJobStatus
-        if: always()
-        run: |
-          LAST_JOB_STATUS=$(gh run list --workflow daily-tests.yaml | grep -oh "completed.*" | head -1 | awk '{print $2}')
-          THIS_JOB_STATUS="${{ job.status }}"
-          if [ "$LAST_JOB_STATUS" != "$THIS_JOB_STATUS" ]; then
-            echo "status changed from $LAST_JOB_STATUS to $THIS_JOB_STATUS"
-          else
-            echo "status is still $THIS_JOB_STATUS"
-          fi
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#       - name: Check last job status
+#         id: lastJobStatus
+#         if: always()
+#         run: |
+#           LAST_JOB_STATUS=$(gh run list --workflow daily-tests.yaml | grep -oh "completed.*" | head -1 | awk '{print $2}')
+#           THIS_JOB_STATUS="${{ job.status }}"
+#           if [ "$LAST_JOB_STATUS" != "$THIS_JOB_STATUS" ]; then
+#             echo "status changed from $LAST_JOB_STATUS to $THIS_JOB_STATUS"
+#           else
+#             echo "status is still $THIS_JOB_STATUS"
+#           fi
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Showcase output variable
-        if: always() && steps.lastJobStatus.outputs.changedState == 'true'
-        run: echo "CHANGED STATE!!!"
+#       - name: Showcase output variable
+#         if: always() && steps.lastJobStatus.outputs.changedState == 'true'
+#         run: echo "CHANGED STATE!!!"
 
 
 
