testing

diff --git a/.github/workflows/artifact-testing.yaml b/.github/workflows/artifact-testing.yaml
--- a/.github/workflows/artifact-testing.yaml
+++ b/.github/workflows/artifact-testing.yaml
@@ -27,16 +27,24 @@ jobs:
       #     done
       - name: Download stuff
         run: |
-          for commit in $(git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}); do
-              git checkout $commit
-              if !(git log -1 --pretty=format:"%s" | grep -q "Change-Id: ")
-              then
-                echo "One or more of the commits in this pull request is missing a Change-ID, which we require for any changes made to gem5. "\
-                "To automatically insert one, run the following:\n f=`git rev-parse --git-dir`/hooks/commit-msg ; mkdir -p $(dirname $f) ; "\
-                "curl -Lo $f https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x $f\n Then amend the commit with git commit --amend --no-edit, and update your pull request."
-                exit 1
-              fi
-          done
+          wget https://dist.gem5.org/dist/develop/images/x86/ubuntu-18-04/x86-ubuntu.img.gz
+      - name: Delete stuff
+        run: |
+          ls -la ./
+          rm -rf ./* || true
+          rm -rf ./.??* || true
+          rm ~/.cache
+          ls -la ./
+          # for commit in $(git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}); do
+          #     git checkout $commit
+          #     if !(git log -1 --pretty=format:"%s" | grep -q "Change-Id: ")
+          #     then
+          #       echo "One or more of the commits in this pull request is missing a Change-ID, which we require for any changes made to gem5. "\
+          #       "To automatically insert one, run the following:\n f=`git rev-parse --git-dir`/hooks/commit-msg ; mkdir -p $(dirname $f) ; "\
+          #       "curl -Lo $f https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x $f\n Then amend the commit with git commit --amend --no-edit, and update your pull request."
+          #       exit 1
+          #     fi
+          # done
 
 
 # name: 'Github Workflow History'
