Update artifact-testing.yaml

diff --git a/.github/workflows/artifact-testing.yaml b/.github/workflows/artifact-testing.yaml
--- a/.github/workflows/artifact-testing.yaml
+++ b/.github/workflows/artifact-testing.yaml
@@ -6,58 +6,152 @@ on:
   # pull_request:
   #   types: [opened, edited, synchronize, ready_for_review]
 
+env:
+  RUN_SCRIPT="configs/example/gem5_library/x86-ubuntu-run-to-tick.py --ticks 1000000"
+  BASELINE_STATS="stats-baseline.txt"
+  COMPARE_STATS="stats-to-compare.txt"
+
 jobs:
-  commits-since-last-run:
-    runs-on: ubuntu-latest
+  stats-output-baseline:
+    runs-on: [self-hosted, linux, x64, build]
+    timeout-minutes: 120     # 2 hours
+    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
     steps:
-    - uses: actions/checkout@v2
+        - uses: actions/checkout@v3
+          with:
+            # Scheduled workflows run on the default branch by default. We
+            # therefore need to explicitly checkout the develop branch.
+            ref: develop
+
+        - name: Compile build/ALL/gem5.opt with ubuntu-22.04_all-dependencies
+          run: /usr/bin/env python3 /usr/bin/scons --ignore-style build/ALL/gem5.opt -j$(nproc)
+
+        - name: Run basic gem5 script
+          run: ./build/ALL/gem5.opt --stats-file="${BASELINE_STATS}" ${RUN_SCRIPT}
+
+        - name: Upload stats JSON
+          uses: actions/upload-artifact@v2
+          with:
+            name: all-stats-json
+            path: m5out/${{ env.BASELINE_STATS }}
+
+  # replication of compiler-tests.sh
+  all-compilers:
+    needs: stats-output-baseline
+    strategy:
+      fail-fast: false
+      matrix:
+        image: [gcc-version-12, gcc-version-11, gcc-version-10, gcc-version-9, gcc-version-8, clang-version-14, clang-version-13, clang-version-12, clang-version-11, clang-version-10, clang-version-9, clang-version-8, clang-version-7, ubuntu-20.04_all-dependencies, ubuntu-22.04_all-dependencies, ubuntu-22.04_min-dependencies]
+        opts: [.opt, .fast]
+    runs-on: [self-hosted, linux, x64, build]
+    timeout-minutes: 2880     # 48 hours
+    container: gcr.io/gem5-test/${{ matrix.image }}:latest
+    steps:
+    - uses: actions/checkout@v3
       with:
         # Scheduled workflows run on the default branch by default. We
         # therefore need to explicitly checkout the develop branch.
         ref: develop
+    - name: Compile build/ALL/gem5${{ matrix.opts }} with ${{ matrix.image }}
+      run: /usr/bin/env python3 /usr/bin/scons --ignore-style build/ALL/gem5${{ matrix.opts }} -j$(nproc)
+      timeout-minutes: 600  # 10 hours
 
-    - name: 'Download artifact'
-      uses: actions/github-script@v6
-      continue-on-error: true
+    # Here we check the binary the compiler produces produces the same stats.
+    - name: Run basic gem5 script
+      run: ./build/ALL/gem5${{ matrix.opts }} --stats-file="${COMPARE_STATS}" ${RUN_SCRIPT}
+
+    - name: Get the baseline stats JSON
+      uses: actions/download-artifact@v2
       with:
-        script: |
-            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
-               owner: context.repo.owner,
-               repo: context.repo.repo,
-               run_id: context.payload.workflow_run.id,
-            });
-            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
-              return artifact.name == "last-scheduled-daily-run-commit"
-            })[0];
-            let download = await github.rest.actions.downloadArtifact({
-               owner: context.repo.owner,
-               repo: context.repo.repo,
-               artifact_id: matchArtifact.id,
-               archive_format: 'zip',
-            });
-            let fs = require('fs');
-            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/last-scheduled-daily-run-commit.zip`, Buffer.from(download.data));
+        name: all-stats-json
 
-    - name: get-last-daily-test-commit
+    - name: Install jq
+      run: apt install jq
+
+    - name: Compare the stats JSONs
       run: |
-        echo "## Commits since last scheduled daily run" >> $GITHUB_STEP_SUMMARY
-        if [ -f last-scheduled-daily-run-commit ]; then
-          prev_commit=$(cat last-scheduled-daily-run-commit)
-          git log --oneline --ancestry-path  --pretty='* [%h](${{ github.server_url }}/${{ github.repository }}/commit/%h) %s ' ${prev_commit}..HEAD >> $GITHUB_STEP_SUMMARY
+        diff <(grep -v "^host" "m5out/${COMPARE_STATS}" ) <(grep -v "^host" "${BASELINE_STATS}")
+        if [ $? -eq 0 ]; then
+          echo "Stats files are the same"
+          exit 0
         else
-          echo "No last-scheduled-daily-run-commit artifact found. This is the first scheduled daily run." >> $GITHUB_STEP_SUMMARY
+          echo "Stats files are different"
+          exit 1
         fi
-    - name: Record this run's commit as last scheduled daily run commit
-      run: echo "$(git rev-parse HEAD)" >last-scheduled-daily-run-commit
 
-    - name: Upload last scheduled daily run commit artifact
-      uses: actions/upload-artifact@v3
+  # Tests the two latest gcc and clang supported compilers against all gem5 compilations.
+  latest-compilers-all-gem5-builds:
+    strategy:
+      fail-fast: false
+      matrix:
+        gem5-compilation: [ARM, ARM_MESI_Three_Level, ARM_MESI_Three_Level_HTM, ARM_MOESI_hammer, Garnet_standalone, GCN3_X86, MIPS, 'NULL', NULL_MESI_Two_Level, NULL_MOESI_CMP_directory, NULL_MOESI_CMP_token, NULL_MOESI_hammer, POWER, RISCV, SPARC, X86, X86_MI_example, X86_MOESI_AMD_Base, VEGA_X86, GCN3_X86]
+        image: [gcc-version-12, clang-version-14]
+        opts: [.opt]
+    runs-on: [self-hosted, linux, x64, build]
+    timeout-minutes: 2880     # 48 hours
+    container: gcr.io/gem5-test/${{ matrix.image }}:latest
+    steps:
+    - uses: actions/checkout@v3
       with:
-        name: last-scheduled-daily-run-commit
-        path: last-scheduled-daily-run-commit
+        # Scheduled workflows run on the default branch by default. We
+        # therefore need to explicitly checkout the develop branch.
+        ref: develop
+    - name: Compile build/${{ matrix.gem5-compilation }}/gem5${{ matrix.opts }} with ${{ matrix.image }}
+      run: /usr/bin/env python3 /usr/bin/scons --ignore-style build/${{ matrix.gem5-compilation }}/gem5${{ matrix.opts }} -j$(nproc)
+      timeout-minutes: 600 # 10 hours
 
-    - name: Cleanup
-      run: rm last-scheduled-daily-run-commit
+# jobs:
+  # commits-since-last-run:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #     with:
+  #       # Scheduled workflows run on the default branch by default. We
+  #       # therefore need to explicitly checkout the develop branch.
+  #       ref: develop
+
+  #   - name: 'Download artifact'
+  #     uses: actions/github-script@v6
+  #     continue-on-error: true
+      # with:
+      #   script: |
+      #       let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
+      #          owner: context.repo.owner,
+      #          repo: context.repo.repo,
+      #          run_id: context.payload.workflow_run.id,
+      #       });
+      #       let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
+      #         return artifact.name == "last-scheduled-daily-run-commit"
+      #       })[0];
+      #       let download = await github.rest.actions.downloadArtifact({
+    #            owner: context.repo.owner,
+    #            repo: context.repo.repo,
+    #            artifact_id: matchArtifact.id,
+    #            archive_format: 'zip',
+    #         });
+    #         let fs = require('fs');
+    #         fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/last-scheduled-daily-run-commit.zip`, Buffer.from(download.data));
+
+    # - name: get-last-daily-test-commit
+    #   run: |
+    #     echo "## Commits since last scheduled daily run" >> $GITHUB_STEP_SUMMARY
+    #     if [ -f last-scheduled-daily-run-commit ]; then
+    #       prev_commit=$(cat last-scheduled-daily-run-commit)
+    #       git log --oneline --ancestry-path  --pretty='* [%h](${{ github.server_url }}/${{ github.repository }}/commit/%h) %s ' ${prev_commit}..HEAD >> $GITHUB_STEP_SUMMARY
+    #     else
+    #       echo "No last-scheduled-daily-run-commit artifact found. This is the first scheduled daily run." >> $GITHUB_STEP_SUMMARY
+    #     fi
+    # - name: Record this run's commit as last scheduled daily run commit
+    #   run: echo "$(git rev-parse HEAD)" >last-scheduled-daily-run-commit
+
+    # - name: Upload last scheduled daily run commit artifact
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: last-scheduled-daily-run-commit
+    #     path: last-scheduled-daily-run-commit
+
+    # - name: Cleanup
+    #   run: rm last-scheduled-daily-run-commit
 
 
           # mkdir -p tests/testing-results
